package com.ning.killbill.generators.ruby;

import java.io.File;
import java.io.FileNotFoundException;
import java.io.FileWriter;
import java.io.IOException;
import java.io.PrintWriter;
import java.io.Writer;
import java.net.URL;
import java.util.List;

import com.ning.killbill.generators.GeneratorException;
import com.ning.killbill.objects.Annotation;
import com.ning.killbill.objects.ClassEnumOrInterface;
import com.ning.killbill.objects.Constructor;
import com.ning.killbill.objects.Field;

import com.google.common.io.Files;
import com.google.common.io.Resources;

public class RubyGenerator extends BaseGenerator {

    private final static String LICENSE_NAME = "RubyLicense.txt";

    private final static int INDENT_LEVEL = 2;
    private final static String DEFAULT_BASE_CLASS = "Resource";

    private final String[] MODULES = {"KillbillClient", "Model"};

    private int curIndent = 0;

    public RubyGenerator() {
        this.curIndent = 0;
    }


    @Override
    protected void generateClass(final ClassEnumOrInterface obj, final File outputDir) throws GeneratorException {
        final File output = new File(outputDir, createFileName(obj.getName()));

        writeLicense(output);

        Writer w = null;
        try {
            w = new FileWriter(output, true);

            writeHeader(w);

            boolean first = true;
            for (int i = 0; i < MODULES.length; i++) {
                if (first) {
                    writeWithIndetation("module " + MODULES[i], w, 0);
                    first = false;
                } else {
                    writeWithIndetation("module " + MODULES[i], w, INDENT_LEVEL);
                }
            }
            //final String baseClass = obj.getSuperBaseClass() != null ? obj.getSuperBaseClass() : DEFAULT_BASE_CLASS;
            final String baseClass = DEFAULT_BASE_CLASS;
            writeWithIndetation("module " + createClassName(obj.getName()) + " < " + baseClass, w, INDENT_LEVEL);
            final Constructor ctor = getJsonCreatorCTOR(obj);
            first = true;
            for (Field f : ctor.getOrderedArguments()) {
                final String attribute = camelToUnderscore(getJsonPropertyAnnotationValue(obj, f));
                if (first) {
                    first = false;
                    writeWithIndetation("attribute: " + attribute, w, INDENT_LEVEL);
                } else {
                    writeWithIndetation("attribute: " + attribute, w, 0);
                }
            }
            writeWithIndetation("end", w, -INDENT_LEVEL);
            for (int i = 0; i < MODULES.length; i++) {
                writeWithIndetation("end", w, -INDENT_LEVEL);
            }
            w.flush();
            w.close();

        } catch (FileNotFoundException e) {
            throw new GeneratorException("Failed to generate file " + obj.getName(), e);
        } catch (IOException e) {
            throw new GeneratorException("Failed to generate file " + obj.getName(), e);
        }
    }

    private void writeLicense(final File output) throws GeneratorException {
        try {
            final URL licenseUrl = Resources.getResource(LICENSE_NAME);
            final File license = new File(licenseUrl.getFile());
            Files.copy(license, output);
        } catch (IllegalArgumentException e) {
            throw new GeneratorException("Cannot find license file " + LICENSE_NAME, e);
        } catch (IOException e) {
            throw new GeneratorException("Failed to write license file " + LICENSE_NAME, e);
        }
    }

    private void writeHeader(final Writer w) throws IOException {
        w.write("\n");
        w.write("\n");
        w.write("#\n");
        w.write("#                       DO NOT EDIT!!!\n");
        w.write("#    File automatically generated by killbill-java-parser (git@github.com:killbill/killbill-java-parser.git)\n");
        w.write("#\n");
        w.write("\n");
        w.write("\n");
    }

    private void writeWithIndetation(final String str, final Writer w, int curIndentOffest) throws IOException {
        curIndent += curIndentOffest;
        for (int i = 0; i < curIndent; i++) {
            w.write(" ");
        }
        w.write(str);
        w.write("\n");
    }

    private static String createFileName(final String objName) {
        return camelToUnderscore(createClassName(objName) + ".rb");
    }

    private static String createClassName(final String objName) {
        return objName.replace("Json", "Attributes");
    }

    private String getJsonPropertyAnnotationValue(final ClassEnumOrInterface obj, final Field f) throws GeneratorException {
        for (Annotation a : f.getAnnotations()) {
            if ("JsonProperty".equals(a.getName())) {
                return a.getValue();
            }
        }
        throw new GeneratorException("Could not find a JsonProperty annotation for object " + obj.getName() + " and field " + f.getName());
    }

    private Constructor getJsonCreatorCTOR(final ClassEnumOrInterface obj) throws GeneratorException {
        final List<Constructor> ctors = obj.getCtors();
        for (Constructor cur : ctors) {
            if (cur.getAnnotations() == null || cur.getAnnotations().size() == 0) {
                continue;
            }
            for (final Annotation a : cur.getAnnotations()) {
                if ("JsonCreator".equals(a.getName())) {
                    return cur;
                }
            }
        }
        throw new GeneratorException("Could not find a CTOR for " + obj.getName() + " with a JsonCreator annotation");
    }
}
